#!/usr/bin/env bash
ROVIO_CONFIG_DIR=$1
LOCALIZATION_MAP_OUTPUT=$2
ROSBAG="out-side-isec-1.bag"
NCAMERA_CALIBRATION="$ROVIO_CONFIG_DIR/origin_self_ncamera_maplab.yaml"
IMU_PARAMETERS_MAPLAB="$ROVIO_CONFIG_DIR/origin_self_imu_maplab.yaml"
IMU_PARAMETERS_ROVIO="$ROVIO_CONFIG_DIR/origin_self_imu_rovio.yaml"
REST=$@

rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --v=2 \
  --ncamera_calibration=$NCAMERA_CALIBRATION  \
  --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB \
  --imu_parameters_rovio=$IMU_PARAMETERS_ROVIO \
  --datasource_type="rosbag" \
  --save_map_folder="$LOCALIZATION_MAP_OUTPUT" \
  --optimize_map_to_localization_map=false \
  --map_builder_save_image_as_resources=false \
  --datasource_rosbag=$ROSBAG $REST \
  --vio_camera_topic_suffix="" 
